Repository great-sprout/PyeonSool, pull requests merged in 2022-07, with the labels that each got.

#238 feat: 키워드 목록 조회 기능 구현
  pyeonsool/src/main/java/toyproject/pyeonsool/initDB.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/MyKeywordCustomRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/MyKeywordCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/MyKeywordRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/MemberService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/AlcoholController.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/HomeController.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/MemberController.java
  pyeonsool/src/main/resources/templates/fragment/header.html
  pyeonsool/src/test/java/toyproject/pyeonsool/repository/KeywordRepositoryTest.java
  pyeonsool/src/test/java/toyproject/pyeonsool/service/MemberServiceTest.java
Labels: 백엔드, 기능

#239 비로그인 상태시 당신의 편술 구현
  pyeonsool/src/main/java/toyproject/pyeonsool/initDB.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/AlcoholKeywordCustomRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/AlcoholKeywordCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/AlcoholRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/MyKeywordCustomRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/MyKeywordCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/HomeController.java
  pyeonsool/src/main/resources/static/css/screens/mainPage.css
  pyeonsool/src/main/resources/templates/mainPage.html
Labels: 백엔드, 기능

#243 마이페이지 내 리뷰 리스트 목록 조회
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/ReviewCustomRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/ReviewCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/ReviewImageDto.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/ReviewImagePathDto.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/ReviewService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/MemberController.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/ReviewController.java
  pyeonsool/src/main/resources/templates/myPage.html
  pyeonsool/src/test/java/toyproject/pyeonsool/repository/ReviewCustomRepositoryImplTest.java
Labels: 백엔드, 기능

#245 마이페이지 내 리뷰 리스트 부분 타임리프 적용 오류 수정
  pyeonsool/src/main/resources/templates/myPage.html
Labels: 백엔드, 기능

#247 like 버튼 클릭 시 alcohol에 likeCount 값 변경
  pyeonsool-class.png
  pyeonsool-table.png
  pyeonsool/src/main/java/toyproject/pyeonsool/domain/Alcohol.java
  pyeonsool/src/main/java/toyproject/pyeonsool/initDB.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/AlcoholCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/AlcoholSearchConditionDto.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholService.java
  pyeonsool/src/test/java/toyproject/pyeonsool/repository/AlcoholRepositoryTest.java
Labels: 백엔드, 기능

#249 당신의 편술 로직 구현&개선
  pyeonsool/src/main/java/toyproject/pyeonsool/initDB.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/AlcoholCustomRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/AlcoholCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/AlcoholKeywordCustomRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/AlcoholKeywordCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/MyKeywordCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholImageDto.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/BestLikeDto.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/HomeController.java
  pyeonsool/src/main/resources/static/css/screens/mainPage.css
  pyeonsool/src/main/resources/static/image/components/blur-pyeonsool.png
  pyeonsool/src/main/resources/static/js/mainPage.js
  pyeonsool/src/main/resources/templates/mainPage.html
  pyeonsool/src/test/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepositoryImplTest.java
Labels: 백엔드, 기능

#250 블러 이미지 css 수정
  pyeonsool/src/main/resources/static/css/screens/mainPage.css
  pyeonsool/src/main/resources/static/js/mainPage.js
  pyeonsool/src/main/resources/templates/mainPage.html
Labels: 백엔드, 기능

#257 목록 페이지 셀렉트 박스 별 정렬
  pyeonsool/src/main/java/toyproject/pyeonsool/domain/Alcohol.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/AlcoholCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/AlcoholSearchConditionDto.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholDto.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/AlcoholController.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/AlcoholSearchForm.java
  pyeonsool/src/main/resources/templates/listPage.html
  pyeonsool/src/test/java/toyproject/pyeonsool/repository/AlcoholRepositoryTest.java
  pyeonsool/src/test/java/toyproject/pyeonsool/service/AlcoholServiceTest.java
Labels: 백엔드, 기능

#267 리뷰 삭제 기능 구현
  pyeonsool/src/main/java/toyproject/pyeonsool/domain/Review.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/ReviewService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/ReviewApiController.java
  pyeonsool/src/main/resources/static/js/myPage.js
  pyeonsool/src/test/java/toyproject/pyeonsool/service/ReviewServiceTest.java
Labels: 백엔드, 기능

#273 마이페이지 내 Lile 리스트 부분 높이 자동 증가
  pyeonsool/src/main/resources/static/css/screens/myPage.css
  pyeonsool/src/main/resources/templates/myPage.html
Labels: 프론트엔드

#281 회원 가입후 마이페이지로 이동시 페이지 오류
  pyeonsool/src/main/resources/templates/myPage.html
Labels: 백엔드, 기능

#282 로그인, 회원가입 검증 미완성
  pyeonsool/src/main/java/toyproject/pyeonsool/web/LoginForm.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/MemberController.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/MemberSaveForm.java
  pyeonsool/src/main/resources/static/css/screens/signIn.css
  pyeonsool/src/main/resources/static/css/screens/signUp.css
  pyeonsool/src/main/resources/templates/signIn.html
  pyeonsool/src/main/resources/templates/signUp.html
Labels: 백엔드, 기능

#291 로그인 예외처리 개선
  pyeonsool/src/main/java/toyproject/pyeonsool/common/exception/PyeonSoolException.java
  pyeonsool/src/main/java/toyproject/pyeonsool/common/exception/form/FormExceptionType.java
  pyeonsool/src/main/java/toyproject/pyeonsool/common/exception/form/IncorrectPasswordException.java
  pyeonsool/src/main/java/toyproject/pyeonsool/common/exception/form/IncorrectUserIdException.java
  pyeonsool/src/main/java/toyproject/pyeonsool/common/exception/form/PyeonSoolFieldException.java
  pyeonsool/src/main/java/toyproject/pyeonsool/common/exception/form/PyeonSoolFormException.java
  pyeonsool/src/main/java/toyproject/pyeonsool/member/sevice/MemberService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/member/web/MemberController.java
  pyeonsool/src/main/resources/static/css/screens/signIn.css
  pyeonsool/src/main/resources/templates/signIn.html
Labels: 백엔드, 리팩터링
