Repository great-sprout/PyeonSool, pull requests merged in 2022-06, with the labels that each got.

#42 관련 추천 상품 슬라이드 기능 구현
  front/css/screens/detailPage.css
  front/html/detailPage.html
  front/js/SlideController.js
  front/js/detailPage.js
Labels: 프론트엔드, 기능

#52 마이 페이지 html, css 구현
  front/css/screens/myPage.css
  front/html/myPage.html
Labels: 프론트엔드

#66 상품 목록 페이지 상품 목록 리스트로 수정
  front/css/screens/listPage.css
  front/html/listPage.html
Labels: 프론트엔드

#71 마이페이지 취향저격 편술 슬릭슬라이드 구현 #53
  front/css/screens/myPage.css
  front/html/myPage.html
  front/js/MyPageSildeController.js
  front/js/myPage.js
Labels: 프론트엔드, 기능

#72 feat: 상품 목록 페이지 베스트 리스트 슬릭 슬라이드 구현
  front/css/screens/listPage.css
  front/html/listPage.html
  front/js/SlideController.js
  front/js/listPage.js
Labels: 프론트엔드

#88 마이페이지 리뷰 등록, 수정시 검증 기능 추가 및 수정 가능한 상태로 변경 구현
  front/css/screens/myPage.css
  front/html/myPage.html
  front/js/myPage.js
Labels: 프론트엔드, 기능

#90 마이페이지 헤더, 푸터 적용
  front/html/myPage.html
Labels: 프론트엔드

#92 마이페이지 취향저격 편술 부분 높이 조정
  front/css/screens/myPage.css
Labels: 프론트엔드

#93 상품 목록 페이지 위치, 크기 조정
  front/css/screens/listPage.css
Labels: 버그, 프론트엔드

#94 리스트 페이지 아이콘 없던 부분 수정
  front/css/screens/listPage.css
  front/html/listPage.html
Labels: 버그, 프론트엔드

#101 상품 목록 페이지 키워드 선택 시 색상 변화
  front/css/screens/listPage.css
  front/html/listPage.html
  front/js/listPage.js
Labels: 프론트엔드

#103 베스트 Like 리스트 위치 수정
  pyeonsool/src/main/resources/static/css/screens/mainPage.css
Labels: 프론트엔드

#105 정렬 키워드 박스 체크박스로 수정
  pyeonsool/src/main/resources/static/css/screens/listPage.css
  pyeonsool/src/main/resources/static/html/listPage.html
Labels: 프론트엔드

#107 상품 목록 페이지 CSS 조정
  pyeonsool/src/main/resources/static/css/screens/listPage.css
  pyeonsool/src/main/resources/static/html/listPage.html
Labels: 버그, 프론트엔드

#109 베스트 Like 카테고리별 리스트 구현
  pyeonsool/src/main/resources/static/css/screens/mainPage.css
  pyeonsool/src/main/resources/static/html/mainPage.html
  pyeonsool/src/main/resources/static/js/mainPage.js
Labels: 프론트엔드, 기능

#129 목록 페이지 이동 & css,js,image 경로 수정
  pyeonsool/src/main/java/toyproject/pyeonsool/web/AlcoholController.java
  pyeonsool/src/main/resources/templates/listPage.html
Labels: 백엔드, 기능

#174 주류 타입 별 데이터 조회 구현
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/AlcoholRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholTypeDto.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/AlcoholApiController.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/AlcoholController.java
  pyeonsool/src/test/java/toyproject/pyeonsool/repository/AlcoholRepositoryTest.java
  pyeonsool/src/test/java/toyproject/pyeonsool/service/AlcoholServiceTest.java
Labels: 백엔드, 기능

#186 내 Like 리스트 목록 조회 기능 구현 (#152)
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/MemberRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/MemberService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/MyPageDto.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/MemberController.java
  pyeonsool/src/test/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepositoryImplTest.java
  pyeonsool/src/test/java/toyproject/pyeonsool/service/AlcoholServiceTest.java
  pyeonsool/src/test/java/toyproject/pyeonsool/service/MemberServiceTest.java
Labels: 백엔드, 기능

#189 listpage keyword 타임리프로 수정
  pyeonsool/src/main/resources/static/css/screens/listPage.css
  pyeonsool/src/main/resources/templates/listPage.html
Labels: 버그, 백엔드

#190 타입별 알콜 데이터 선호하는 멤버 아이디 추가
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholTypeDto.java
  pyeonsool/src/test/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepositoryImplTest.java
  pyeonsool/src/test/java/toyproject/pyeonsool/service/AlcoholServiceTest.java
Labels: 백엔드, 기능

#192 listpage 알콜 별 좋아요 멤버 수 출력
  pyeonsool/src/main/resources/static/css/screens/listPage.css
  pyeonsool/src/main/resources/templates/listPage.html
Labels: 백엔드, 기능

#204 type별 데이터 알콜 별 좋아요 부분 숫자로 수정
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholTypeDto.java
  pyeonsool/src/main/resources/templates/listPage.html
  pyeonsool/src/test/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepositoryImplTest.java
Labels: 버그, 백엔드

#213 마이페이지 Thymeleaf 적용
  pyeonsool/src/main/java/toyproject/pyeonsool/web/MemberController.java
  pyeonsool/src/main/resources/templates/myPage.html
Labels: 백엔드, 기능

#223 상품 목록 페이지 페이징 처리
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/AlcoholRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholDto.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/AlcoholController.java
  pyeonsool/src/main/resources/static/css/screens/listPage.css
  pyeonsool/src/main/resources/templates/listPage.html
  pyeonsool/src/test/java/toyproject/pyeonsool/repository/AlcoholRepositoryTest.java
  pyeonsool/src/test/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepositoryImplTest.java
  pyeonsool/src/test/java/toyproject/pyeonsool/service/AlcoholServiceTest.java
Labels: 백엔드, 기능

#231 마이페이지에서 내 Like 리스트 취소 기능 구현
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepository.java
  pyeonsool/src/main/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepositoryImpl.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholImageDto.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/AlcoholService.java
  pyeonsool/src/main/java/toyproject/pyeonsool/service/MyPageDto.java
  pyeonsool/src/main/java/toyproject/pyeonsool/web/MemberController.java
  pyeonsool/src/main/resources/static/css/screens/myPage.css
  pyeonsool/src/main/resources/static/js/myPage.js
  pyeonsool/src/main/resources/templates/myPage.html
  pyeonsool/src/test/java/toyproject/pyeonsool/repository/PreferredAlcoholCustomRepositoryImplTest.java
  pyeonsool/src/test/java/toyproject/pyeonsool/service/AlcoholServiceTest.java
Labels: 백엔드, 기능

#233 마이페이지 내 Like 리스트 목록 선택 시 해당 상품 상세 페이지로 이동
  pyeonsool/src/main/resources/templates/myPage.html
Labels: 백엔드, 기능
